### PR TITLE
Create tachidesk-jui

### PR DESCRIPTION
**Pull request by Witchilich**

### CODE REVIEW

**Comment by se35710** [comment]
I think this would be better suited in @Ash258's [Jetbrains](https://github.com/Ash258/Scoop-JetBrains) bucket.

**Comment by Ash258** [comment]
/unsubscribe

Please never tag me in anything related to the java. I do not use java and want to be as far away from it as possible.

This has nothing to do with Jetbrains. It only uses the Jetbrains compose "framework" (or whatever it is).
It is some weird reader for comics or whatever.

**Comment by Witchilich** [comment]
@se35710 It needs Java Runtime Environment to run which is in this bucket.

**Comment by se35710** [comment]
You can use: `"depends": "java/openjdk"`, and submit it to another better matching bucket. This one is mainly for just JDK/JRE variants.

Ref: https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties

**Pull request closed without merging**
