### PR TITLE
BREAKING: Add JDK suffix to all JDK manifests

### LINKED ISSUE #100: Rename AdoptOpenJDK manifests to Adoptium
Rename all `adoptX` to `adoptopenjdkX`. So users can search AdoptOpenJDK with keyword `adopt` or `openjdk` or `adoptopenjdk`.

e.g.
`adopt13-hotspot.json` ->`adoptopenjdk13-hotspot.json`

### PR DESCRIPTION
**Pull request by se35710**
### Breaking PR
This PR will break updating all JDK manifests, since it will rename the manifest to include --jdk. To update installed JDK:s, the user will have to uninstall their JDK manifests, and then reinstall with the new name, eg:

- `scoop uninstall corretto`
- `scoop install corretto-jdk`

We have also renamed the AdoptOpenJDK manifests from adopt to adoptopenjdk. Users need to reinstall with the same process as the example above.

### Reasons why
Right now searching for a JDK (`scoop search jdk`) only returns a small subset of the JDK's that are available in the Java repo. This is especially true for Java 8, where the only returned choices are [ojdkbuild8](https://github.com/ScoopInstaller/Java/blob/master/bucket/ojdkbuild8.json) and [ojdkbuild8-full](https://github.com/ScoopInstaller/Java/blob/master/bucket/ojdkbuild8-full.json), where there are multiple alternatives available.

### See also
Closes #100 
Replaces #104

### CODE REVIEW

**Comment by chawyehsu** [comment]
Why not also rename adoptX to adoptopenjdkX?

**Comment by Ash258** [comment]
I do not use java so I pretty much do not care for this.

**Comment by se35710** [comment]
> Why not also rename adoptX to adoptopenjdkX?

We could. It will add 7 characters to already lengthy manifests names, though.

**Comment by rasa** [comment]
Is this just to fix the search results? 

What about instead adding a
```
“keywords”: [“jdk”],
```
and modify the search function to look in this field?

**Comment by rasa** [comment]
Also, is scoop graceful when an installed app effectively disappears (as git doesn’t really track renames)? Does it inform the user during a `scoop update` or even a `scoop list`? How much work would it be to determine a rename inside a git commit? Especially when the manifest got tweaked at the same time?

To help with reliably identifying renames, perhaps we add a:
```
“was”: “old-name”,
```
or if a bucket move:
```
“was”: “old-bucket/old-name”,
```
which could allow scoop to explain how to recover from the rename. It could even be automated, say with `scoop update -y`, where `-y` means to answer “y” to all prompts.

**Comment by chawyehsu** [comment]
> We could. It will add 7 characters to already lengthy manifests names, though.

7 more characters is not a big problem for a already lengthyyyyyyyyyyy name, lol.

**Comment by se35710** [comment]
I still agree a lot with what was said in #100 and with @rasa comments above. Searching should be extended with keywords and/or searching through the description of the manifest. I tried to search for an existing feature request, but could not find any. Should I create one in [scoop](https://github.com/lukesampson/scoop/issues)?

**Comment by chawyehsu** [comment]
@se35710 
Searchable description and keywords is a missing feature for Scoop. 

> I tried to search for an existing feature request, but could not find any. Should I create one in scoop?

Yes, you can do it if you have free time and are willing to make it happen, the `core` development is inactive currently though.

**Pull request closed without merging**
