### PR TITLE
Adding 8 intellij-jbr manifests

### LINKED ISSUE #427: (Request) Add jbr11 and jbr17
HomePage: https://github.com/JetBrains/JetBrainsRuntime
jbr11: https://github.com/JetBrains/JetBrainsRuntime/tree/jbr11
jbr17: https://github.com/JetBrains/JetBrainsRuntime/tree/jbr17

### PR DESCRIPTION
**Pull request by Zliced13**
Should I add a jbr11 despite that version not being maintained any more by JetBrains?

Closes #427

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Zliced13** [comment]
God, why is the bot such a picky bitch when it comes to `autoupdate`?

**Review by se35710 — APPROVED** [review]

**Comment by se35710** [comment]
Please remove the draft label once your are done pushing commits and it's ready for review.

**Comment by Zliced13** [comment]
I'm done pushing commits, could you please remove the draft label?

**Review by se35710 — APPROVED** [review]

**Pull request merged**
