### PR TITLE
Add GraalVM CE v19.0.0 - Polyglot Virtual Machine for JVM, JavaScript, LLVM..

### PR DESCRIPTION
**Pull request by cyparu**
GraalVM is a polyglot JVM/JIT supporting Java/Scala/Kotlin, JavaScript/NodeJS, Ruby, Python, R + any-LLVM based languages, with fast & compact AOT/native image executables
https://www.graalvm.org

GraalVM 19.0 Released - First production release of the revolutionary polyglot virtual machine / @GraalVM
https://medium.com/graalvm/announcing-graalvm-19-4590cf354df8
https://www.graalvm.org/docs/release-notes/#1900
https://www.graalvm.org/downloads/
https://www.graalvm.org/docs/reference-manual/graal-updater/
https://www.graalvm.org/docs/reference-manual/aot-compilation/

### CODE REVIEW

**Comment by se35710** [comment]
`checkver` does not work, because up their `vm-<version>` tagging. Please add `regex` in the manifest.

@r15ch13 Should this be in Java or in Extras?

**Comment by cyparu** [comment]
> `checkver` does not work, because up their `vm-<version>` tagging. Please add `regex` in the manifest.
> 
> @r15ch13 Should this be in Java or in Extras?
It look like this will do the trick. 

```json
"checkver": {
      "github": "https://github.com/oracle/graal",
      "re": "vm-([\\d\\w.-]+)"
 },
```

@r15ch13, @se35710  I committed under Java bucket since GraalVM is a JVM related technology.

**Comment by niheaven** [comment]
This should be in `extra`, I think.

**Comment by cyparu** [comment]
> Looks good, thank you for your contribution!
With all the approval process being complete now, when should we expect to have the PR merged with Windows users enjoying GraalVM over a simple `scoop install graalvm` ?

**Comment by se35710** [comment]
There we go!

**Comment by niheaven** [comment]
I'm waiting for `gu`,but maybe, next version?

**Comment by cyparu** [comment]
> 
> 
> I'm waiting for `gu`,but maybe, next edition?

According to the release notes ( https://www.graalvm.org/docs/release-notes/#1900 ) just *Early Adopter Windows Support* is available now (with no `gu` updater).
BTW, I've just tweeted about this `scoop` GraalVM **_premiere_** 🚀 https://twitter.com/Jaguard/status/1129030479846498305

**Pull request merged**
