### PR TITLE
dragonwell17-jdk: Update version to 17.0.8.0.8-17.0.8

### PR DESCRIPTION
**Pull request by romeoahmed**
See https://github.com/dragonwell-project/dragonwell17/wiki/Alibaba-Dragonwell-17-Standard-Edition-Release-Notes#1708087

The regex seems to be outdated, I made some small changes and don't know if it will work as expected

Currently dragonwell17 only has **standard** edtion, but it is foreseeable that there will be an **extended** edition in the future

Closes #XXXX

Relates to #XXXX

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romeoahmed** [comment]
Well luckily it works fine, sorry for the many invalid PRs submitted earlier

**Review by se35710 — CHANGES_REQUESTED** [review]
Please revert the name change, at least until they release the extended version. If they do, lets figure out the naming policy for scoop then. If the name is changed, all previous installations of dragonwell will be orphaned, and won't update.

**Comment by romeoahmed** [comment]
Ok, just reverted. The same goes for other pull requests.

**Review by se35710 — APPROVED** [review]
Thanks!

**Comment by romeoahmed** [comment]
Thank you for your hard work bro(*^_^*), I didn't think carefully about the name change before.

**Comment by se35710** [comment]
No worries, and it me and the rest of the Scoop community who should thank you for your contribution!

**Pull request merged**
