### PR TITLE
Zulu enhancements

### LINKED ISSUE #514: Migrate from Zulu OpenJDK Discovery API to Azul Metadata API
## Bug Report

**Package Name:** `zulu*`

### Current Behaviour

Currently, Azul Zulu packages are using the discovery API (<https://api.azul.com/zulu/download/>).

### Expected Behaviour

Azul Zulu packages should utilize the new metadata API (<https://api.azul.com/metadata/v1/>)

### Additional context/output

In accordance with <https://docs.azul.com/core/metadata-api-migration>.

Azul now support [CRaC](https://www.azul.com/products/components/crac/) on their JDKs beginning on version 17 by default, currently `zulu17-jdk` and `zulu-jdk` packages cannot update correctly due to the incorrect regex trying to match the default CRaC (`*-ca-crac-*`) support.

It's also worth mentioning that the LTS version of 21 is missing from the bucket (#509).
Zulu packages beginning from 21 should drop support for 32-bit architecture in accordance with [JEP 449](https://openjdk.org/jeps/449).

### Possible Solution

- Replace supported `zulu*` packages' `checkver` and `autoupdate` links with the new metadata API.
- Drop support for 32bit architecture on `zulu-*` and `zulufx-*` as per JEP 449.

We should discuss about making a separate package for the CRaC support.

### PR DESCRIPTION
**Pull request by ryansuhartanto**
Should resolves #514.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ryansuhartanto** [comment]
I'll use this `jsonpath` to filter the version and product UUIDs
```
$..distro_version,package_uuid
```
And then I use `regex` to match it (example: <https://regex101.com/r/bYBxsK/1>)
```regex
\[\s*\[\s*(?<major>\d+),\s*(?<minor>\d+),\s*(?<patch>\d+),\s*\d\s*\],\s*"(?<amd64>[\w-]+)"(?:,\s*\[\s*(?:\d+,?\s*)+\],\s*"(?<i686>[\w-]+)")\s*\]
```

**Comment by ryansuhartanto** [comment]
I think I found a bug when doing `json_path`.
```
$ json_path '[{"availability_type":"CA","distro_version":[17,48,15,0],"download_url":"https://cdn.azul.com/zulu/bin/zulu17.48.15-ca-fx-jre17.0.10-win_x64.zip","java_version":[17,0,10],"latest":true,"name":"zulu17.48.15-ca-fx-jre17.0.10-win_x64.zip","openjdk_build_number":7,"package_uuid":"cef00b50-77db-400a-afdd-b9e391e44631","product":"zulu"},{"availability_type":"CA","distro_version":[17,48,15,0],"download_url":"https://cdn.azul.com/zulu/bin/zulu17.48.15-ca-fx-jre17.0.10-win_i686.zip","java_version":[17,0,10],"latest":true,"name":"zulu17.48.15-ca-fx-jre17.0.10-win_i686.zip","openjdk_build_number":7,"package_uuid":"25351721-5e7e-4eef-a0ef-0c3686b38631","product":"zulu"}]' "$..['distro_version','package_uuid']" $null $false $false
[
  17,
  48,
  15,
  0
]\ncef00b50-77db-400a-afdd-b9e391e44631\n[
  17,
  48,
  15,
  0
]\n25351721-5e7e-4eef-a0ef-0c3686b38631
```

**Comment by ryansuhartanto** [comment]
Product UUIDs is discarded using this technique, but this is the best I can do for the current Scoop version by utilizing `include_fields`.

**Comment by eijckron** [comment]
@se35710 You have approved most of the recent PR's. What is needed to get this PR merged?

**Comment by se35710** [comment]
> @se35710 You have approved most of the recent PR's. What is needed to get this PR merged?

Just a little unsure about the JEP 449 and the removal of x86-32 binaries. Going to merge it now.

**Pull request merged**
