### PR TITLE
microsoft-jdk: Add arm64 architecture

### PR DESCRIPTION
**Pull request by dahlia**
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by HUMORCE** [comment]
Please consider adding arm64 support for all versions.

```
'java' bucket:
  microsoft-jdk (17.0.7)
  microsoft-lts-jdk (17.0.7)
  microsoft11-jdk (11.0.19)
  microsoft16-jdk (16.0.2.7.1)
  microsoft17-jdk (17.0.7)
```

**Comment by dahlia** [comment]
@HUMORCE I added arm64 support for all versions, and rebased the commits on the current master.

**Pull request merged**
