### PR TITLE
dragonwell-jdk-extended: Add version 8.16.17-8.0.382 and 11.0.20.16-11.0.20

### LINKED ISSUE #482: [Request] dragonwell8-jdk-extended&dragonwell11-jdk-extended
### Criteria

For a package to be acceptable in the Java bucket, it should be:

- [x] a runtime environment or software development kit for Java
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)
- [x] downloadable without having to sign in or use user-dependant cookies

### Information

**Name:** dragonwell8-jdk-extended and dragonwell11-jdk-extended

**Description:** Alibaba Dragonwell, a downstream version of OpenJDK, is the in-house OpenJDK implementation at Alibaba (with extensive custom features optimized for cloud computing environments)

**Homepage:** https://dragonwell-jdk.io/

**Download link(s):** https://dragonwell-jdk.io/

**Some indication of popularity/repute:** 4k and 509 stars (same as the standard version)

**License:** GPL-2.0-only WITH Classpath-exception-2.0

### PR DESCRIPTION
**Pull request by romeoahmed**
See 
- [Dragonwell8 Extended Edition Release Notes](https://github.com/dragonwell-project/dragonwell8/wiki/Alibaba-Dragonwell8-Extended-Edition-Release-Notes)
- [Dragonwell11 Extended Edition Release Notes](https://github.com/dragonwell-project/dragonwell11/wiki/Alibaba-Dragonwell-11-Extended-Edition-Release-Notes)

Closes #482 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by romeoahmed** [comment]
Interestingly, the local checkver reported an error, but the check of github action passed.
```bash
dragonwell11-jdk-extended: couldn't match '(dragonwell-standard-(?<dragon>[\d.]+)?_jdk-(?<jdk>[\d.]+)(?:(?<b>-[\d+])|-ga))/(Alibaba_Dragonwell_Standard_(?<version>[\d.+]+))' in https://github.com/dragonwell-project/dragonwell11/releases/latest
```

**Comment by se35710** [comment]
> Interestingly, the local checkver reported an error, but the check of github action passed.

GitHub requires an API token to use their API. There is a scoop setting to add the token to your local installation.

**Comment by brainos233** [comment]
> [Your changes do not pass checks.](https://github.com/ScoopInstaller/GithubActions/wiki/Pull-Request-Checks)
> 
> ### dragonwell11-jdk-extended
> * [x]  Description
> * [x]  License
> * [x]  Hashes
> * [ ]  Checkver
> * [ ]  Autoupdate
> * [ ]  Autoupdate Hash Extraction
> 
> ### dragonwell8-jdk-extended
> * [x]  Description
> * [x]  License
> * [x]  Hashes
> * [ ]  Checkver
> * [ ]  Autoupdate
> * [ ]  Autoupdate Hash Extraction

**Review by se35710 — APPROVED** [review]

**Pull request merged**
