### PR TITLE
Update GraalVM to 19.3.0

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by niheaven** [comment]
Why not add a seperate `java8` manifest?

**Comment by se35710** [comment]
I agree with @niheaven, please add `graalvm8.json` and `graalvm11.json`.

**Comment by nightscape** [comment]
Should I additionally keep the `graalvm.json` as the Java 11 version?

**Comment by nightscape** [comment]
@niheaven @se35710 amended the two additional files.

**Pull request merged**
